[2023-11-21T17:21:20.605+0500] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: competition.process_data manual__2023-11-21T12:20:10.289456+00:00 [queued]>
[2023-11-21T17:21:20.649+0500] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: competition.process_data manual__2023-11-21T12:20:10.289456+00:00 [queued]>
[2023-11-21T17:21:20.650+0500] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2023-11-21T17:21:20.709+0500] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): process_data> on 2023-11-21 12:20:10.289456+00:00
[2023-11-21T17:21:20.730+0500] {standard_task_runner.py:57} INFO - Started process 18384 to run task
[2023-11-21T17:21:20.740+0500] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'competition', 'process_data', 'manual__2023-11-21T12:20:10.289456+00:00', '--job-id', '18', '--raw', '--subdir', 'DAGS_FOLDER/competition_score.py', '--cfg-path', '/tmp/tmp05roh_hr']
[2023-11-21T17:21:20.748+0500] {standard_task_runner.py:85} INFO - Job 18: Subtask process_data
[2023-11-21T17:21:21.020+0500] {task_command.py:416} INFO - Running <TaskInstance: competition.process_data manual__2023-11-21T12:20:10.289456+00:00 [running]> on host Acer
[2023-11-21T17:21:21.521+0500] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='makar' AIRFLOW_CTX_DAG_ID='competition' AIRFLOW_CTX_TASK_ID='process_data' AIRFLOW_CTX_EXECUTION_DATE='2023-11-21T12:20:10.289456+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-11-21T12:20:10.289456+00:00'
[2023-11-21T17:21:21.529+0500] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-11-21T17:21:21.533+0500] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python3 /home/makar/MLops_3/scripts/process_data.py']
[2023-11-21T17:21:21.600+0500] {subprocess.py:86} INFO - Output:
[2023-11-21T17:21:25.262+0500] {subprocess.py:93} INFO - Traceback (most recent call last):
[2023-11-21T17:21:25.264+0500] {subprocess.py:93} INFO -   File "/home/makar/MLops_3/scripts/process_data.py", line 4, in <module>
[2023-11-21T17:21:25.265+0500] {subprocess.py:93} INFO -     df = pd.read_csv('datasets/data.csv')
[2023-11-21T17:21:25.266+0500] {subprocess.py:93} INFO -   File "/home/makar/.local/lib/python3.10/site-packages/pandas/util/_decorators.py", line 211, in wrapper
[2023-11-21T17:21:25.269+0500] {subprocess.py:93} INFO -     return func(*args, **kwargs)
[2023-11-21T17:21:25.270+0500] {subprocess.py:93} INFO -   File "/home/makar/.local/lib/python3.10/site-packages/pandas/util/_decorators.py", line 331, in wrapper
[2023-11-21T17:21:25.272+0500] {subprocess.py:93} INFO -     return func(*args, **kwargs)
[2023-11-21T17:21:25.278+0500] {subprocess.py:93} INFO -   File "/home/makar/.local/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 950, in read_csv
[2023-11-21T17:21:25.280+0500] {subprocess.py:93} INFO -     return _read(filepath_or_buffer, kwds)
[2023-11-21T17:21:25.281+0500] {subprocess.py:93} INFO -   File "/home/makar/.local/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 605, in _read
[2023-11-21T17:21:25.285+0500] {subprocess.py:93} INFO -     parser = TextFileReader(filepath_or_buffer, **kwds)
[2023-11-21T17:21:25.286+0500] {subprocess.py:93} INFO -   File "/home/makar/.local/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 1442, in __init__
[2023-11-21T17:21:25.299+0500] {subprocess.py:93} INFO -     self._engine = self._make_engine(f, self.engine)
[2023-11-21T17:21:25.304+0500] {subprocess.py:93} INFO -   File "/home/makar/.local/lib/python3.10/site-packages/pandas/io/parsers/readers.py", line 1735, in _make_engine
[2023-11-21T17:21:25.309+0500] {subprocess.py:93} INFO -     self.handles = get_handle(
[2023-11-21T17:21:25.310+0500] {subprocess.py:93} INFO -   File "/home/makar/.local/lib/python3.10/site-packages/pandas/io/common.py", line 856, in get_handle
[2023-11-21T17:21:25.312+0500] {subprocess.py:93} INFO -     handle = open(
[2023-11-21T17:21:25.313+0500] {subprocess.py:93} INFO - FileNotFoundError: [Errno 2] No such file or directory: 'datasets/data.csv'
[2023-11-21T17:21:25.648+0500] {subprocess.py:97} INFO - Command exited with return code 1
[2023-11-21T17:21:25.710+0500] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2023-11-21T17:21:25.728+0500] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=competition, task_id=process_data, execution_date=20231121T122010, start_date=20231121T122120, end_date=20231121T122125
[2023-11-21T17:21:25.825+0500] {standard_task_runner.py:104} ERROR - Failed to execute job 18 for task process_data (Bash command failed. The command returned a non-zero exit code 1.; 18384)
[2023-11-21T17:21:25.947+0500] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-11-21T17:21:26.119+0500] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
