[2023-11-21T17:07:10.049+0500] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: competition.get_data manual__2023-11-21T12:01:31.077020+00:00 [queued]>
[2023-11-21T17:07:10.087+0500] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: competition.get_data manual__2023-11-21T12:01:31.077020+00:00 [queued]>
[2023-11-21T17:07:10.088+0500] {taskinstance.py:1361} INFO - Starting attempt 2 of 2
[2023-11-21T17:07:10.141+0500] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): get_data> on 2023-11-21 12:01:31.077020+00:00
[2023-11-21T17:07:10.157+0500] {standard_task_runner.py:57} INFO - Started process 14647 to run task
[2023-11-21T17:07:10.166+0500] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'competition', 'get_data', 'manual__2023-11-21T12:01:31.077020+00:00', '--job-id', '15', '--raw', '--subdir', 'DAGS_FOLDER/competition_score.py', '--cfg-path', '/tmp/tmp0ojbxujg']
[2023-11-21T17:07:10.171+0500] {standard_task_runner.py:85} INFO - Job 15: Subtask get_data
[2023-11-21T17:07:10.411+0500] {task_command.py:416} INFO - Running <TaskInstance: competition.get_data manual__2023-11-21T12:01:31.077020+00:00 [running]> on host Acer
[2023-11-21T17:07:10.787+0500] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='makar' AIRFLOW_CTX_DAG_ID='competition' AIRFLOW_CTX_TASK_ID='get_data' AIRFLOW_CTX_EXECUTION_DATE='2023-11-21T12:01:31.077020+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-11-21T12:01:31.077020+00:00'
[2023-11-21T17:07:10.796+0500] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-11-21T17:07:10.798+0500] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python3 /home/makar/MLops_3/scripts/get_data.py']
[2023-11-21T17:07:10.833+0500] {subprocess.py:86} INFO - Output:
[2023-11-21T17:07:18.718+0500] {subprocess.py:93} INFO - Traceback (most recent call last):
[2023-11-21T17:07:18.719+0500] {subprocess.py:93} INFO -   File "/home/makar/MLops_3/scripts/get_data.py", line 13, in <module>
[2023-11-21T17:07:18.720+0500] {subprocess.py:93} INFO -     df_full.to_csv('datasets/data.csv')
[2023-11-21T17:07:18.721+0500] {subprocess.py:93} INFO -   File "/home/makar/.local/lib/python3.10/site-packages/pandas/util/_decorators.py", line 211, in wrapper
[2023-11-21T17:07:18.722+0500] {subprocess.py:93} INFO -     return func(*args, **kwargs)
[2023-11-21T17:07:18.723+0500] {subprocess.py:93} INFO -   File "/home/makar/.local/lib/python3.10/site-packages/pandas/core/generic.py", line 3720, in to_csv
[2023-11-21T17:07:18.724+0500] {subprocess.py:93} INFO -     return DataFrameRenderer(formatter).to_csv(
[2023-11-21T17:07:18.724+0500] {subprocess.py:93} INFO -   File "/home/makar/.local/lib/python3.10/site-packages/pandas/util/_decorators.py", line 211, in wrapper
[2023-11-21T17:07:18.725+0500] {subprocess.py:93} INFO -     return func(*args, **kwargs)
[2023-11-21T17:07:18.726+0500] {subprocess.py:93} INFO -   File "/home/makar/.local/lib/python3.10/site-packages/pandas/io/formats/format.py", line 1189, in to_csv
[2023-11-21T17:07:18.728+0500] {subprocess.py:93} INFO -     csv_formatter.save()
[2023-11-21T17:07:18.729+0500] {subprocess.py:93} INFO -   File "/home/makar/.local/lib/python3.10/site-packages/pandas/io/formats/csvs.py", line 241, in save
[2023-11-21T17:07:18.730+0500] {subprocess.py:93} INFO -     with get_handle(
[2023-11-21T17:07:18.731+0500] {subprocess.py:93} INFO -   File "/home/makar/.local/lib/python3.10/site-packages/pandas/io/common.py", line 734, in get_handle
[2023-11-21T17:07:18.732+0500] {subprocess.py:93} INFO -     check_parent_directory(str(handle))
[2023-11-21T17:07:18.733+0500] {subprocess.py:93} INFO -   File "/home/makar/.local/lib/python3.10/site-packages/pandas/io/common.py", line 597, in check_parent_directory
[2023-11-21T17:07:18.734+0500] {subprocess.py:93} INFO -     raise OSError(rf"Cannot save file into a non-existent directory: '{parent}'")
[2023-11-21T17:07:18.735+0500] {subprocess.py:93} INFO - OSError: Cannot save file into a non-existent directory: 'datasets'
[2023-11-21T17:07:19.331+0500] {subprocess.py:97} INFO - Command exited with return code 1
[2023-11-21T17:07:19.390+0500] {taskinstance.py:1937} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2023-11-21T17:07:19.405+0500] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=competition, task_id=get_data, execution_date=20231121T120131, start_date=20231121T120710, end_date=20231121T120719
[2023-11-21T17:07:19.457+0500] {standard_task_runner.py:104} ERROR - Failed to execute job 15 for task get_data (Bash command failed. The command returned a non-zero exit code 1.; 14647)
[2023-11-21T17:07:19.510+0500] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-11-21T17:07:19.639+0500] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
